import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { 
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <div className="container mx-auto p-3.5">
          <div className="md:flex min-h-screen items-center justify-center">
            <div className="flex flex-col items-center gap-6">
               <Image
                  src="/af.png"
                  alt="Afternoon"
                  width={80}
                  height={80}                  
                  sizes="(max-width: 600px) 50px, 80px"
                  className="mx-auto w-20 h-20 max-[600px]:w-12.5 max-[600px]:h-12.5"
                />                
              <Card className="w-xl max-w-full">
                <CardHeader>
                  <CardTitle><h1 className="text-2xl font-bold">Sign In</h1></CardTitle>
                  <CardDescription>
                    Sign in to your account to continue.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {children} 
                </CardContent>
              </Card>     
            </div>  
          </div>
        </div>
      </body>
    </html>
  );
}
